remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter_opts:
    guess_lang: false

# Title of your site
title: "UCI Math 134 Notes"
description: "Left for Xiaokang to change. Modify the description in the _config.yaml file. "